[colors]
# Polar Night (Backgrounds) & Snow Storm (Texts)
background=2e3440ff
text=d8dee9ff

# Prompt & Input text colors
prompt=88c0d0ff
input=e5e9f0ff

# Frost (Selection bar & active match colors)
selection=434c5eff
selection-text=eceff4ff
match=81a1c1ff
selection-match=88c0d0ff

# Nord Border
border=3b4252ff
