preload = ~/tipi/wallpapers/nord-es.jpg

# Use 'hyprctl monitors' to find your monitor names (e.g., DP-1, eDP-1)
wallpaper = HDMI-A-1,~/tipi/wallpapers/nord-es.jpg

splash = false  # Disable the bottom splash text
ipc = on        # Keep IPC on for dynamic changes
