preload = ~/tipi/wallpapers/nord-dark/by_upload2_2560-nord-dark.png

# Use 'hyprctl monitors' to find your monitor names (e.g., DP-1, eDP-1)
wallpaper = HDMI-A-1,~/tipi/wallpapers/nord-dark/by_upload2_2560-nord-dark.png

splash = false  # Disable the bottom splash text
ipc = on        # Keep IPC on for dynamic changes
